version: 2
jobs:
  build:
    working_directory: ~/dockerapp
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
